### PR TITLE
Fixes #1130

### LINKED ISSUE #1130: Schema creation failed with permission error in preparedDatabases
Hi team,

We are trying to create multiple databases using the 'preparedDatabases'.
**There is no issue while creating only 1 database and schema. But the issue occurs when we start adding the second database& schema and more.**

**With the below configuration, the first database & schema passed is created successfully,  but the second and other databases and schema  creates error.**

Below is the configuration of the "cluster values.yaml"

```
spec:
  additionalVolumes:
  - mountPath: /var/run/postgresql
    name: empty
    targetContainers:
    - all
    volumeSource:
      emptyDir: {}
  numberOfInstances: 1
  patroni:
    pg_hba:
    - hostssl a3s      a3s_a3s_owner_user      all md5
    - hostssl all      postgres                all md5
    - host    all      all                     all md5
  postgresql:
    version: "12"
  preparedDatabases:
    a3sdb:
      schemas:
        a3sschema:
          defaultRoles: true
          defaultUsers: true
    a3s:
      schemas:
        a3s:
          defaultRoles: true
          defaultUsers: true
    a3seb:
      schemas:
        a3seb:
          defaultRoles: true
          defaultUsers: true
```
The database is getting created but the schema creation failed with permission error:

```
time="2020-09-02T14:39:15Z" level=info msg="creating database schema \"a3s\" owner \"a3s_a3s_owner\"" cluster-name=pg-testing/postgres-test-interval pkg=cluster
time="2020-09-02T14:39:15Z" level=info msg="creating database schema \"a3sschema\" owner \"a3sdb_a3sschema_owner\"" cluster-name=pg-testing/postgres-test-interval pkg=cluster
time="2020-09-02T14:39:15Z" level=debug msg="closing database connection" cluster-name=pg-testing/postgres-test-interval pkg=cluster
time="2020-09-02T14:39:15Z" level=warning msg="attempted to close an empty db connection object" cluster-name=pg-testing/postgres-test-interval pkg=cluster
**time="2020-09-02T14:39:15Z" level=error msg="could not sync prepared databases: could not execute create database schema: pq: permission denied for database a3s" cluster-name=pg-testing/postgres-test-interval pkg=cluster**
time="2020-09-02T14:39:15Z" level=info msg="cluster has been updated" cluster-name=pg-testing/postgres-test-interval pkg=controller worker=1
```

**The above log  shows , the "a3s" schema is created successfully but the "a3sschema" schema creation failed with permission error.**

Could you please  suggest how do we  create multiple databases using "preparedDatabases"

Thanks

### PR DESCRIPTION
**Pull request by neelasha-09**
Hi,

Problem was: defer should not be used in for loops. 
Link:  https://stackoverflow.com/questions/45617758/defer-in-the-loop-what-will-be-better 

Fixes #1130 

```
time="2020-09-11T13:08:11Z" level=debug msg="syncing roles" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=debug msg="closing database connection" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=info msg="syncing databases" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=info msg="creating database \"a3db\" owner \"a3db_owner\"" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=info msg="creating database \"a4db\" owner \"a4db_owner\"" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=debug msg="closing database connection" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=info msg="syncing prepared databases" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=info msg="Opened preparedDbName: a2db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=info msg="Working on preparedDbName: a2db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:16Z" level=info msg="doing:creating database schema schemaName:\"a2schema2\" schemaOwner:\"a2db_a2schema2_owner\" dnOwner:\"a2db_owner\" databaseName:\"a2db\" statement:\"SET ROLE TO \\\"%s\\\"; CREATE SCHEMA IF NOT EXISTS \\\"%s\\\" AUTHORIZATION \\\"%s\\\"\" operation:\"create database schema\"" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="doing:creating database schema schemaName:\"a2schema1\" schemaOwner:\"a2db_a2schema1_owner\" dnOwner:\"a2db_owner\" databaseName:\"a2db\" statement:\"SET ROLE TO \\\"%s\\\"; CREATE SCHEMA IF NOT EXISTS \\\"%s\\\" AUTHORIZATION \\\"%s\\\"\" operation:\"create database schema\"" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="Opened preparedDbName: a3db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="Working on preparedDbName: a3db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="Opened preparedDbName: a4db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="Working on preparedDbName: a4db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="Opened preparedDbName: a1db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="Working on preparedDbName: a1db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="doing:creating database schema schemaName:\"a1schema1\" schemaOwner:\"a1db_a1schema1_owner\" dnOwner:\"a1db_owner\" databaseName:\"a1db\" statement:\"SET ROLE TO \\\"%s\\\"; CREATE SCHEMA IF NOT EXISTS \\\"%s\\\" AUTHORIZATION \\\"%s\\\"\" operation:\"create database schema\"" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=debug msg="closing database connection" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="Closed preparedDbName: a1db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=warning msg="attempted to close an empty db connection object" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="Closed preparedDbName: a1db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=warning msg="attempted to close an empty db connection object" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="Closed preparedDbName: a1db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=warning msg="attempted to close an empty db connection object" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="Closed preparedDbName: a1db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=error msg="could not sync prepared databases: could not execute create database schema: pq: permission denied for database a2db" cluster-name=kafka-fix/postgres-sebpg3 pkg=cluster
time="2020-09-11T13:08:17Z" level=info msg="cluster has been updated" cluster-name=kafka-fix/postgres-sebpg3 pkg=controller worker=3
```

### CODE REVIEW

**Comment by neelasha-09** [comment]
Hi @Jan-M and @FxKu 

We would appreciate a quick review and merge of this PR as it’s very valuable to us.

Thanks

File: pkg/cluster/database.go [hunk 1]
```diff
@@ -329,7 +329,8 @@ func (c *Cluster) execCreateDatabaseSchema(databaseName, schemaName, dbOwner, sc
 	if !c.databaseSchemaNameValid(schemaName) {
 		return nil
 	}
-	c.logger.Infof("%s %q owner %q", doing, schemaName, schemaOwner)
+	//c.logger.Infof("%s %q owner %q", doing, schemaName, schemaOwner)
+	c.logger.Debugf("%s with schemaName:%q schemaOwner:%q dbOwner:%q databaseName:%q statement:%q operation:%q", doing, schemaName, schemaOwner, dbOwner, databaseName, statement , operation)
```
Comment (FxKu) [inline pkg/cluster/database.go:333]: can you revert this change? This debug line is not aligned with the rest of the logs

File: pkg/cluster/sync.go [hunk 2]
```diff
@@ -715,6 +713,12 @@ func (c *Cluster) syncPreparedDatabases() error {
 		if err := c.syncExtensions(preparedDB.Extensions); err != nil {
 			return err
 		}
+
+		if err := c.closeDbConn(); err != nil {
+			c.logger.Errorf("could not close database connection: %v", err)
+		} else {
+			c.logger.Debugf("closed preparedDbName: %s", preparedDbName)
+		}
```
Comment (FxKu) [inline pkg/cluster/sync.go:721]: I would remove the else block. Don't see much value logging this info.

File: pkg/cluster/sync.go [hunk 3]
```diff
@@ -695,13 +695,11 @@ func (c *Cluster) syncPreparedDatabases() error {
 	for preparedDbName, preparedDB := range c.Spec.PreparedDatabases {
 		if err := c.initDbConnWithName(preparedDbName); err != nil {
 			return fmt.Errorf("could not init connection to database %s: %v", preparedDbName, err)
+		} else {
+			c.logger.Debugf("opened preparedDbName: %s", preparedDbName)
```
Comment (FxKu) [inline pkg/cluster/sync.go:699]: same as for closing: I think this log line is not needed

File: pkg/cluster/sync.go [hunk 4]
```diff
@@ -695,13 +695,11 @@ func (c *Cluster) syncPreparedDatabases() error {
...
 		}
-		defer func() {
-			if err := c.closeDbConn(); err != nil {
-				c.logger.Errorf("could not close database connection: %v", err)
-			}
-		}()
 
+		c.logger.Debugf("working on preparedDbName: %s", preparedDbName)
```
Comment (FxKu) [inline pkg/cluster/sync.go:702]:
```suggestion
		c.logger.Debugf("syncing prepared database %q", preparedDbName)
```

**Comment by FxKu** [comment]
Hey @neelasha-09. Cool that you found the issue. Sorry was in vacation. Can you reflect my comments and we'll merge it. Have to look, if I've used the defer within loops someone else.

File: pkg/cluster/sync.go (hunk 3 above)
Comment (neelasha-09) [reply pkg/cluster/sync.go:699]: We can remove, but this info was very valuable in figuring out what actions does OPR do automatically when handling preparedDbs.

File: pkg/cluster/sync.go (hunk 2 above)
Comment (neelasha-09) [reply pkg/cluster/sync.go:721]: > Hey @neelasha-09. Cool that you found the issue. Sorry was in vacation. Can you reflect my comments and we'll merge it. Have to look, if I've used the defer within loops someone else.

We already checked and it's here: #1130

File: pkg/cluster/sync.go (hunk 4 above)
Comment (neelasha-09) [reply pkg/cluster/sync.go:702]: Ok, Approved

File: pkg/cluster/sync.go (hunk 3 above)
Comment (FxKu) [reply pkg/cluster/sync.go:699]: I can image that it helped solving the issue, but the operator opens and closes connections several times. We shouldn't log that. It should be enough to have this extra debug line `syncing prepared database ...`.

File: pkg/cluster/sync.go (hunk 2 above)
Comment (FxKu) [reply pkg/cluster/sync.go:721]: Ah, thanks.

File: pkg/cluster/database.go (hunk 1 above)
Comment (neelasha-09) [reply pkg/cluster/database.go]: reverted as requested.

**Comment by neelasha-09** [comment]
@FxKu - debug msg have been removed as requested.

**Comment by FxKu** [comment]
:+1:

**Comment by sdudoladov** [comment]
:+1:

**Comment by sdudoladov** [comment]
@neelasha-09 thank you for the contribution :+1:
