### PR TITLE
choose switchover candidate based on lag and role

### LINKED ISSUE #109: Manual failover: improve health check of replica
We observed the operator terminating a master pod once a replica pod reached running state but as the replica pod had a significant WAL backlog it was not promotable by Patroni. This led to a downtime for as long as it took to reschedule the other pod and promote that pod to master again.

Needs to basicall also compare WAL delay on replica to be within the max replication lag.

### LINKED ISSUE #600: Improve failover during rolling updates
We observed a situation where a switchover succeeded although a replica had substantial replication lag. It may indicate an error in processing [`POST` calls to the Patroni API](https://github.com/zalando/postgres-operator/blob/0b75a899208a459b912b71c42c1493149d0efda2/pkg/util/patroni/patroni.go#L50)

related #109

### LINKED ISSUE #1686: Switchover fails randomly in synchronous replication
- **Which image of the operator are you using?** e.g. registry.opensource.zalan.do/acid/postgres-operator:v1.7.0
- **Where do you run it - cloud or metal? Kubernetes or OpenShift?** GCP
- **Are you running Postgres Operator in production?** no
- **Type of issue?** Bug report

Here is my cluster manifest:

```yaml
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: foo-cluster
  namespace: default
spec:
  teamId: "foo"
  numberOfInstances: 3
  volume:
    size: 1Gi
  postgresql:
    version: "13"
  patroni:
    synchronous_mode: true
```

Before performing the rolling update:

```shell-session
$ kubectl exec foo-cluster-0 -- patronictl list
+ Cluster: foo-cluster (7030642225746063429) --------+----+-----------+
| Member        | Host      | Role         | State   | TL | Lag in MB |
+---------------+-----------+--------------+---------+----+-----------+
| foo-cluster-0 | 10.4.0.16 | Replica      | running |  4 |         0 |
| foo-cluster-1 | 10.4.1.10 | Leader       | running |  4 |           |
| foo-cluster-2 | 10.4.0.15 | Sync Standby | running |  4 |         0 |
+---------------+-----------+--------------+---------+----+-----------+
```

Before performing the switchover:

```shell-session
$ kubectl exec foo-cluster-0 -- patronictl list
+ Cluster: foo-cluster (7030642225746063429) --------+----+-----------+
| Member        | Host      | Role         | State   | TL | Lag in MB |
+---------------+-----------+--------------+---------+----+-----------+
| foo-cluster-0 | 10.4.0.17 | Sync Standby | running |  4 |         0 |
| foo-cluster-1 | 10.4.1.10 | Leader       | running |  4 |           |
| foo-cluster-2 | 10.4.0.18 | Replica      | running |  4 |         0 |
+---------------+-----------+--------------+---------+----+-----------+
```

and:

```shell-session
$ kubectl logs foo-cluster-1
...
2021-11-15 04:22:28,454 INFO: received failover request with leader=foo-cluster-1 candidate=foo-cluster-2 scheduled_at=None
2021-11-15 04:22:28,474 INFO: Got response from foo-cluster-2 http://10.4.0.18:8008/patroni: {"state": "running", "postmaster_start_time": "2021-11-15 04:22:27.147246+00:00", "role": "replica", "server_version": 130004, "cluster_unlocked": false, "xlog": {"received_location": 134217728, "replayed_location": 135242840, "replayed_timestamp": "2021-11-15 04:18:58.350110+00:00", "paused": false}, "timeline": 4, "database_system_identifier": "7030642225746063429", "patroni": {"version": "2.1.1", "scope": "foo-cluster"}}
2021-11-15 04:22:28,604 INFO: Lock owner: foo-cluster-1; I am foo-cluster-1
2021-11-15 04:22:28,612 WARNING: Failover candidate=foo-cluster-2 does not match with sync_standbys=foo-cluster-0
2021-11-15 04:22:28,612 WARNING: manual failover: members list is empty
2021-11-15 04:22:28,612 WARNING: manual failover: no healthy members found, failover is not possible
2021-11-15 04:22:28,612 INFO: Cleaning up failover key
...
(foo-cluster-1 is going to be shutdown and recreated...)
```

After completing the rolling update:

```shell-session
$ kubectl exec foo-cluster-0 -- patronictl list
+ Cluster: foo-cluster (7030642225746063429) --------+----+-----------+
| Member        | Host      | Role         | State   | TL | Lag in MB |
+---------------+-----------+--------------+---------+----+-----------+
| foo-cluster-0 | 10.4.0.17 | Leader       | running |  5 |           |
| foo-cluster-1 | 10.4.1.11 | Replica      | running |  5 |         0 |
| foo-cluster-2 | 10.4.0.18 | Sync Standby | running |  5 |         0 |
+---------------+-----------+--------------+---------+----+-----------+
```

I also got:

```shell-session
$ kubectl get events --sort-by=.lastTimestamp
...
2m11s       Normal    Update                    postgresql/foo-cluster                          Performing rolling update
2m11s       Normal    Killing                   pod/foo-cluster-0                               Stopping container postgres
111s        Normal    Scheduled                 pod/foo-cluster-0                               Successfully assigned default/foo-cluster-0 to gke-cluster-1-default-pool-f03fb5a7-3whg
111s        Normal    SuccessfulCreate          statefulset/foo-cluster                         create Pod foo-cluster-0 in StatefulSet foo-cluster successful
101s        Normal    SuccessfulAttachVolume    pod/foo-cluster-0                               AttachVolume.Attach succeeded for volume "pvc-9f2ee3a4-e211-4d64-afd5-14beef28685d"
93s         Normal    Created                   pod/foo-cluster-0                               Created container postgres
93s         Normal    Started                   pod/foo-cluster-0                               Started container postgres
93s         Normal    Pulled                    pod/foo-cluster-0                               Container image "registry.opensource.zalan.do/acid/spilo-14:2.1-p3" already present on machine
89s         Normal    Killing                   pod/foo-cluster-2                               Stopping container postgres
61s         Normal    Scheduled                 pod/foo-cluster-2                               Successfully assigned default/foo-cluster-2 to gke-cluster-1-default-pool-f03fb5a7-3whg
61s         Normal    SuccessfulCreate          statefulset/foo-cluster                         create Pod foo-cluster-2 in StatefulSet foo-cluster successful
49s         Normal    SuccessfulAttachVolume    pod/foo-cluster-2                               AttachVolume.Attach succeeded for volume "pvc-0215d8ca-3ca7-4535-b29c-c40c203c75b2"
43s         Normal    Pulled                    pod/foo-cluster-2                               Container image "registry.opensource.zalan.do/acid/spilo-14:2.1-p3" already present on machine
43s         Normal    Started                   pod/foo-cluster-2                               Started container postgres
43s         Normal    Created                   pod/foo-cluster-2                               Created container postgres
39s         Normal    Switchover                postgresql/foo-cluster                          Switching over from "foo-cluster-1" to "default/foo-cluster-2"
38s         Normal    Switchover                postgresql/foo-cluster                          Switchover from "foo-cluster-1" to "default/foo-cluster-2" FAILED: could not switch over from "foo-cluster-1" to "default/foo-cluster-2": patroni returned 'Failover failed'
38s         Normal    Killing                   pod/foo-cluster-1                               Stopping container postgres
19s         Normal    SuccessfulCreate          statefulset/foo-cluster                         create Pod foo-cluster-1 in StatefulSet foo-cluster successful
19s         Normal    Scheduled                 pod/foo-cluster-1                               Successfully assigned default/foo-cluster-1 to gke-cluster-1-default-pool-f03fb5a7-hwqt
12s         Normal    SuccessfulAttachVolume    pod/foo-cluster-1                               AttachVolume.Attach succeeded for volume "pvc-d6dcc1ad-1653-48d4-a9df-de14c7b3f639"
9s          Normal    Created                   pod/foo-cluster-1                               Created container postgres
9s          Normal    Started                   pod/foo-cluster-1                               Started container postgres
9s          Normal    Pulled                    pod/foo-cluster-1                               Container image "registry.opensource.zalan.do/acid/spilo-14:2.1-p3" already present on machine
5s          Normal    Update                    postgresql/foo-cluster                          Rolling update done - pods have been recreated
```

This problem is caused by the fact that the switchover destination is randomly selected from replicas, and in the above example, the switchover from `foo-cluster-1` (Master) to `foo-cluster-2` (Replica) fails.

https://github.com/zalando/postgres-operator/blob/1eafd688d0a100a8a1c5c76fd87e29e09b14d209/pkg/cluster/pod.go#L462

https://github.com/zalando/postgres-operator/blob/1eafd688d0a100a8a1c5c76fd87e29e09b14d209/pkg/cluster/util.go#L528-L530

When using synchronous replication, the switchover destination should be selected from synchronous standbys.

### PR DESCRIPTION
**Pull request by FxKu**
Change 1: When attempting a switchover, try it only on a replica that has no replication lag. In case synchronous replication is enabled there will be a replica with `sync_standby` role which should be chosen instead for switchover.

Change 2: In case the switchover is not executed or failing, return an error instead of emitting a `Warning`. Before we were always continuing by replacing the master pod anyway - producing downtime. Now, the master keeps running on an outdated pod. But, the Pod will have the rolling-update flag and the operator will notice it on the next sync and try another failover. It can be, that the failover just took longer, e.g. because taking a CHECKPOINT took longer than Patroni API waits to respond to the user. In this ideal case only a replica would be recreated. In worst case, a switchover might be retried on each sync. But this should be fixed by the admin anyway.

fixes #1686 
fixes #109
fixes #600

### CODE REVIEW

File: pkg/cluster/pod.go [hunk 1]
```diff
@@ -475,6 +480,57 @@ func (c *Cluster) recreatePods(pods []v1.Pod, switchoverCandidates []spec.Namesp
...
+
+	if len(syncCandidates) > 0 {
+		return candidates[rand.Intn(len(syncCandidates))], nil
+	}
+	if len(candidates) > 0 {
+		return candidates[rand.Intn(len(candidates))], nil
+	}
+
+	if len(skipReasons) > 0 {
+		err = fmt.Errorf("no replica suitable for switchover: %s", strings.Join(skipReasons, `','`))
```
Comment (FxKu) [inline pkg/cluster/pod.go:526]:
```suggestion
		err = fmt.Errorf("no replica suitable for switchover: %s", strings.Join(skipReasons, `', '`))
```
```suggestion
		err = fmt.Errorf("no replica suitable for switchover: %s", strings.Join(skipReasons, `','`))
```

File: pkg/cluster/pod.go [hunk 2]
```diff
@@ -475,6 +481,50 @@ func (c *Cluster) recreatePods(pods []v1.Pod, switchoverCandidates []spec.Namesp
...
+	if len(syncCandidates) > 0 {
+		sort.Slice(syncCandidates, func(i, j int) bool { return syncCandidates[i].LagInMB < syncCandidates[j].LagInMB })
+		return spec.NamespacedName{Namespace: master.Namespace, Name: syncCandidates[0].Name}, nil
+	}
+	if len(candidates) > 0 {
+		sort.Slice(candidates, func(i, j int) bool { return candidates[i].LagInMB < candidates[j].LagInMB })
+		return spec.NamespacedName{Namespace: master.Namespace, Name: candidates[0].Name}, nil
+	}
+
+	return spec.NamespacedName{}, fmt.Errorf("no switchover candidate found")
```
Comment (sdudoladov) [inline pkg/cluster/pod.go:525]: why does it return the empty `spec.NamespacedName{}` and not `nil` in case of error ?

File: pkg/cluster/types.go [hunk 3]
```diff
@@ -14,11 +14,11 @@ import (
...
-	// Master role
-	Master PostgresRole = "master"
-
-	// Replica role
-	Replica PostgresRole = "replica"
+	Master        PostgresRole = "master"
+	Replica       PostgresRole = "replica"
+	Leader        PostgresRole = "leader"
+	StandbyLeader PostgresRole = "standby_leader"
+	SyncStandby   PostgresRole = "sync_standby"
```
Comment (sdudoladov) [inline pkg/cluster/types.go:21]: I feel there is a comment missing here:
1. how does operator treat differently `Master`, `StandbyLeader` on the one hand and  `Leader` on the other ? Both `Master` and `StandbyLeader` are leaders. 
2. `SyncStanbdy` is still a `Replica`

While it is still possible to figure it out from the code, a short comment about why these are *not* completely independent states is worthy.

File: pkg/util/patroni/patroni.go [hunk 4]
```diff
@@ -175,6 +177,20 @@ func (p *Patroni) SetConfig(server *v1.Pod, config map[string]interface{}) error
...
+	Members []ClusterMember `json:"members"`
+}
+
+// ClusterMember cluster member data from Patroni API
+type ClusterMember struct {
+	Name     string `json:"name"`
+	Role     string `json:"role"`
+	State    string `json:"state"`
+	Timeline int    `json:"timeline"`
+	LagInMB  int    `json:"lag"`
```
Comment (sdudoladov) [inline pkg/util/patroni/patroni.go:191]: Does Patroni always return lag in MB and not simply in bytes ?
for example, the `patronictl` [converts bytes to MB](https://github.com/zalando/patroni/blob/fce889cd048da605c60fe607f19d7c82f526359d/patroni/ctl.py#L815)

File: pkg/cluster/pod.go (hunk 2 above)
Comment (FxKu) [reply pkg/cluster/pod.go:525]: Go says: "cannot use nil (untyped nil value) as spec.NamespacedName value in return statement" :smiley:

File: pkg/util/patroni/patroni.go (hunk 4 above)
Comment (FxKu) [reply pkg/util/patroni/patroni.go]: renamed to just `Lag`

File: pkg/cluster/types.go (hunk 3 above)
Comment (FxKu) [reply pkg/cluster/types.go:24]: `master` and `replica` are Spilo roles. The other ones role names returned by Patroni's `cluster` endpoint. Added comments

File: pkg/util/patroni/patroni.go (hunk 4 above)
Comment (FxKu) [reply pkg/util/patroni/patroni.go]: hm maybe lag is reserved for something else:
```
cannot unmarshal string into Go struct field ClusterMember.members.lag of type int
```
renamed it back, since I think it's always in MB.

**Comment by FxKu** [comment]
:+1:

**Comment by Jan-M** [comment]
:+1:
